cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'coreutils'
brew 'git'
brew 'node'
brew 'bat'
brew 'openssl'
brew 'wget'
brew 'youtube-dl'
brew 'python3'
brew 'ipython'
brew 'tree'
brew 'jq'
brew 'yarn'
brew 'pgcli'
brew 'hub'
brew 'awscli'
brew 'aws-shell'
brew 'pipenv'
brew 'go'

cask 'iterm2'
cask 'alfred'
cask '1password'
cask 'dropbox'
cask 'google-chrome'
cask 'slack'
cask 'visual-studio-code'
cask 'forklift'
cask 'bartender'
cask 'iina'
cask 'appcleaner'
cask 'docker'
cask 'jitouch'
cask 'postman'
cask 'whatsapp'
cask 'istat-menus'
cask 'postgres'
cask 'caffeine'
cask 'dbeaver-community'
cask 'pycharm'
cask 'clipy'
cask 'cleanmymac'
cask 'charles'
cask 'gitter'
cask 'paw'
cask 'rocket'
cask 'ngrok'
cask 'virtualbox'
cask 'virtualbox-extension-pack'

# Quick Look Plugins
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'
