cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'

brew 'coreutils'
brew 'git'
brew 'git-extras'
brew 'github/gh/gh'
brew 'node'
brew 'bat'
brew 'openssl'
brew 'wget'
brew 'youtube-dl'
brew 'python'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'pyenv-virtualenvwrapper'
brew 'rbenv'
brew 'jenv'
brew 'ipython'
brew 'tree'
brew 'jq'
brew 'yarn'
brew 'awscli'
brew 'aws-shell'
brew 'go'
# https://github.com/Peltoche/lsd/issues/199#issuecomment-494218334
brew 'lsd'
brew 'switchaudio-osx'
brew 'git-delta'
brew 'pre-commit'
brew 'maccy'
brew 'fzf'

cask 'iterm2'
cask 'alfred'
cask 'slack'
cask 'visual-studio-code'
cask 'bartender'
cask 'iina'
cask 'appcleaner'
cask 'docker'
cask 'whatsapp'
cask 'paw'
cask 'rocket'
cask 'the-unarchiver'
cask 'authy'
cask 'macupdater'
cask 'font-fira-code'
cask 'font-hack-nerd-font'
cask 'meld'

# Quick Look Plugins
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'

