#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# Install Mac App Store apps from mas-cli
# You may need to manually log in to MAS first
cat mas_apps.txt | xargs mas install

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
